/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_faturrahman_1855201018;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Cyber Play
 */
public class administrator_kasir extends javax.swing.JFrame {

    /**
     * Creates new form administrator_kasir
     */
    public administrator_kasir() {
        initComponents();
        this.setTitle("aplikasi database toko");
        this.setLocationRelativeTo(this);
        koneksi konek = new koneksi();
        konek.koneksi();
        status.setText(konek.koneksis);
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        in_nmbr = new javax.swing.JTextField();
        ad_simpan = new javax.swing.JButton();
        in_jnsbr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        in_stbr = new javax.swing.JTextField();
        in_hrgbr = new javax.swing.JTextField();
        ad_hapus = new javax.swing.JButton();
        ad_cari = new javax.swing.JButton();
        ad_update = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        in_nobr = new javax.swing.JTextField();
        pilih = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adm_tabel = new javax.swing.JTable();
        in_resert = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        in_nmbr.setBackground(new java.awt.Color(204, 204, 204));
        in_nmbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_nmbrActionPerformed(evt);
            }
        });

        ad_simpan.setBackground(new java.awt.Color(255, 0, 51));
        ad_simpan.setText("SIMPAN");
        ad_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_simpanActionPerformed(evt);
            }
        });

        in_jnsbr.setBackground(new java.awt.Color(204, 204, 204));
        in_jnsbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_jnsbrActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("NAMA BARANG");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("JENIS BARANG");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("HARGA BARANG");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("STOK BARANG");

        in_stbr.setBackground(new java.awt.Color(204, 204, 204));
        in_stbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_stbrActionPerformed(evt);
            }
        });

        in_hrgbr.setBackground(new java.awt.Color(204, 204, 204));
        in_hrgbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_hrgbrActionPerformed(evt);
            }
        });

        ad_hapus.setBackground(new java.awt.Color(255, 0, 51));
        ad_hapus.setText("HAPUS");
        ad_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_hapusActionPerformed(evt);
            }
        });

        ad_cari.setBackground(new java.awt.Color(255, 0, 51));
        ad_cari.setText("CARI");
        ad_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_cariActionPerformed(evt);
            }
        });

        ad_update.setBackground(new java.awt.Color(255, 0, 51));
        ad_update.setText("+");
        ad_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_updateActionPerformed(evt);
            }
        });

        status.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("NOMOR BARANG");

        in_nobr.setBackground(new java.awt.Color(204, 204, 204));
        in_nobr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_nobrActionPerformed(evt);
            }
        });

        pilih.setBackground(new java.awt.Color(255, 0, 51));
        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih pencarian-", "nomor barang", "nama barang", "jenis barang", "harga barang", "stok barang" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_nmbr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_jnsbr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_hrgbr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_stbr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_nobr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ad_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih, 0, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ad_cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ad_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ad_simpan)))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(in_nobr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_nmbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_jnsbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(in_hrgbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(in_stbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_simpan)
                    .addComponent(ad_hapus)
                    .addComponent(ad_cari)
                    .addComponent(ad_update)
                    .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adm_tabel.setBackground(new java.awt.Color(0, 51, 153));
        adm_tabel.setForeground(new java.awt.Color(204, 204, 204));
        adm_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nomorbarang", "namabarang", "jenisbarang", "stokbarang", "hargabarang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        adm_tabel.setGridColor(new java.awt.Color(0, 255, 255));
        adm_tabel.setSelectionBackground(new java.awt.Color(204, 255, 255));
        adm_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adm_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adm_tabel);

        in_resert.setBackground(new java.awt.Color(255, 0, 51));
        in_resert.setText("resert");
        in_resert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_resertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(in_resert)
                .addGap(190, 190, 190))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(in_resert)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("administrator");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selectBynobr(int nobr) throws SQLException {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datatoko where nomorbarang like '%" + nobr + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectBynmbr(String nmbr) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datatoko where namabarang like '%" + nmbr + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByjnbr(String jnbr) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datatoko where jenisbarang like '%" + jnbr + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByhrgbr(int hrbr) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datatoko where hargabarang like '" + hrbr + "'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectBystbr(int stbr) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datatoko where stokbarang like '" + stbr + "'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

//    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
//        
//        // TODO add your handling code here:
//    }                                    
    Statement pst;
    ResultSet rs;

    public void table() {
        koneksi konek = new koneksi();
        konek.koneksi();
        try {
            String sql = "select * from datatoko";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void in_nmbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_nmbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_nmbrActionPerformed

    private void in_jnsbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_jnsbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_jnsbrActionPerformed

    private void in_stbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_stbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_stbrActionPerformed

    private void in_hrgbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_hrgbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_hrgbrActionPerformed

    private void ad_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_cariActionPerformed
        if (pilih.getSelectedIndex() == 1) {

            try {
                selectBynobr(Integer.parseInt(in_nobr.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(administrator_kasir.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (pilih.getSelectedIndex() == 2) {
            selectBynmbr(in_nmbr.getText());
        } else if (pilih.getSelectedIndex() == 3) {
            selectByjnbr(in_jnsbr.getText());
        } else if (pilih.getSelectedIndex() == 4) {
            selectByhrgbr(Integer.parseInt(in_hrgbr.getText()));

        } else if (pilih.getSelectedIndex() == 5) {
            selectBystbr(Integer.parseInt(in_stbr.getText()));

        } else {
            table();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ad_cariActionPerformed

    private void ad_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_updateActionPerformed
        // TODO add your handling code here:
        koneksi konek = new koneksi();
        konek.koneksi();

        update ubah = new update();
        String nmbr = in_nmbr.getText();
        String nobr = in_nobr.getText();
        String jnsbr = in_jnsbr.getText();
        String stbr = in_stbr.getText();
        String hrgbr = in_hrgbr.getText();

        ubah.update(Integer.parseInt(nobr), nmbr, Integer.parseInt(stbr), jnsbr, Integer.parseInt(hrgbr));

        table();
    }//GEN-LAST:event_ad_updateActionPerformed

    private void ad_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_simpanActionPerformed
        insert in = new insert();
        int nobr = Integer.parseInt(in_nobr.getText());
        String nmbr = in_nmbr.getText();
        int stbr = Integer.parseInt(in_stbr.getText());
        int hrgbr = Integer.parseInt(in_hrgbr.getText());
        String jnsbr = in_jnsbr.getText();
        in.insert(nobr, nmbr, stbr, jnsbr, hrgbr);

        table();

        // TODO add your handling code here:
    }//GEN-LAST:event_ad_simpanActionPerformed

    private void adm_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adm_tabelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) adm_tabel.getModel(); //create a model
        int selectedRowIndex = adm_tabel.getSelectedRow(); //get selected row
        int id = (int) dtm.getValueAt(selectedRowIndex, 0); //get the primary key to fetch data.

        koneksi konek = new koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datatoko where nomorbarang like '%" + id + "%'";
            pst = (Statement) konek.con.prepareStatement(sql);
            ResultSet rs = rs = pst.executeQuery(sql);

            while (rs.next()) {    //u can use normal query
                in_nobr.setText(rs.getString("nomorbarang"));
                in_stbr.setText(rs.getString("stokbarang"));
                in_jnsbr.setText(rs.getString("jenisbarang"));
                in_nmbr.setText(rs.getString("namabarang"));
                in_hrgbr.setText(rs.getString("hargabarang"));
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_adm_tabelMouseClicked

    private void in_nobrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_nobrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_nobrActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ad_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_hapusActionPerformed
        koneksi konek = new koneksi();
        konek.koneksi();

        delete del = new delete();
        del.delete(Integer.parseInt(in_nobr.getText()));

        table();
        // TODO add your handling code here:
    }//GEN-LAST:event_ad_hapusActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        aplikasikasir a = new aplikasikasir();
        a.setVisible(true);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void in_resertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_resertActionPerformed
        // TODO add your handling code here:
        in_nobr.setText("");
        in_stbr.setText("");
        in_jnsbr.setText("");
        in_nmbr.setText("");
        in_hrgbr.setText("");

        table();
    }//GEN-LAST:event_in_resertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrator_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrator_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrator_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrator_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrator_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad_cari;
    private javax.swing.JButton ad_hapus;
    private javax.swing.JButton ad_simpan;
    private javax.swing.JButton ad_update;
    private javax.swing.JTable adm_tabel;
    private javax.swing.JTextField in_hrgbr;
    private javax.swing.JTextField in_jnsbr;
    private javax.swing.JTextField in_nmbr;
    private javax.swing.JTextField in_nobr;
    private javax.swing.JButton in_resert;
    private javax.swing.JTextField in_stbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
